### ISSUE TITLE
Cannot change tables name values.

### ISSUE THREAD

**Issue by Docblumav** [ayeressian/db-viewer-component#22]
I am trying your react component through your example in stackblitz. I can modify the json to add some new tables, change column's name but if I don't have table school, class and student, the viewer won't work.
I was wondering if it is on purpose or not.
You could simply reproduce the bug by changing in your stackblitz exemple the table name school.

**Comment by ayeressian** [comment]
@Docblumav it worked for me it rendered empty view. I strongly suggest to create an app on your machine and test this lib there. Stackblitz is just showing a demos.
